### ISSUE TITLE
Wipe `gen-cache/` during update !?

### ISSUE THREAD

**Issue by AnotherKamila** [netsec-ethz/scionlab#246]
TODO define what exactly must be deleted under which conditions.

@AnotherKamila will look into how, but currently does know what.

**Comment by AnotherKamila** [comment]
https://www.debian.org/doc/debian-policy/ch-maintainerscripts.html#summary-of-ways-maintainer-scripts-are-called seems useful.

**Comment by matzf** [comment]
Just to clarify the first point: the files that must be removed are `/var/lib/scion/*` (specifically, the `*.db` files in this directory).

We've always been talking about "gen-cache" because that's the name of the equivalent directory when using the setup with supervisord (e.g. running a local topology). In the packaged setup, there is actually nothing called "gen-cache". Sorry if that caused confusion.

**Comment by matzf** [comment]
See [scion-builder!100](https://gitlab.inf.ethz.ch/PRV-PERRIG/scionlab/scion-builder/-/merge_requests/100).
