### ISSUE TITLE
Support any service such as bwtestserver, sensorserver, etc and new ones

### ISSUE THREAD

**Issue by juagargi** [netsec-ethz/scionlab#298]
The coordinator has knowledge of some services at the moment (`bwtester`, etc), but for some deployments --such as SIGCOMM or other tutorials-- we would like to maintain some other services configured and running, such as the `example_shttp_fileserver` or others. These services have to be restarted when `scionlab.target` restarts; otherwise they stop working.
Allowing a generic service to be configured would solve this problem if the new services that need to be run do not need to understand any changes regarding topologies, etc. Simply a command line to be run for start / stop / restart services would suffice.
Would this be feasible? Any other cleaner alternatives?

**Comment by matzf** [comment]
Alternative proposal; the `scionlab-config` script should generally be more tolerant to local changes, in particular it would be useful if a user can add a service (like the sig) to the `scionlab.target` without this being overwritten.
A simple way to implement this would be to store the list of the services that the coordinator added to `scionlab.target` to the `scionlab-config.json` file, so that in a future run, the `scionlab-config` script can confidently disable services that are removed from the coordinators configuration but keep locally modifications intact.

This should allow to use the coordinator for only the "core" service configuration and simply "get out of the way" to allow using normal systemd routine to run e.g. the fileserver you mention.

**Comment by matzf** [comment]
Implemented in #308, as described above.
