### ISSUE TITLE
Port clashes and PortMap

### ISSUE THREAD

**Issue by juagargi** [netsec-ethz/scionlab#318]
Our `PortMap` is currently used to avoid port clashes when creating border routers.
We have found a problem (fixed by #317 ) where there was a clash in a host, between the control service internal port `CS_PORT` and a border router internal port that reached up to the same value (30254 at the moment of this ticket).
Check the following:
- could we define three valid ranges for the border routers?
- also change the value of the ports from other services that sit in these ranges (e.g. `SD_TCP_PORT = 30255`)? Even if they were TCP, so debugging is easier.
- take care of other possible port clashes, like Prometheus ports for BRs with `SD_PROM_PORT`

**Comment by FR4NK-W** [comment]
The 'ports' tracked in PortMap are SCION/UDP ports, as used in the SCION control plane and SCION applications.
Potential for port clashes exist between the control service (CS) control plane (inter-AS) port (but not the intra-AS port), the border router control plane port, the SIG control/data plane port and any 'SCION native' application running on the same host.

We should definitely define port ranges dedicated to control plane services and enforce these, since those are only SCION/UDP ports.
Regular IP application like prometheus cannot clash in that context, but using non-overlapping port ranges can reduce confusion while debugging.

**Comment by juagargi** [comment]
Another temporary fix related to this issue is #321

**Comment by matzf** [comment]
Note: the CS ports that we use (30x54)  no longer match the "defaults" described in the wiki; it has changed to 30x52.

**Comment by matzf** [comment]
A higher level view of this issue: the problems here are due to the mixed way that these ports are defined.
a) some ports (external router interface ports and router control and internal ports) are defined by an attribute of the object
b) some ports (router monitoring port) are defined as an expression _based on_ an attribute of the object
c) some ports come from constants

When defining the ports stored in attributes, we avoid clashes with the constant ports -- if these constants ever change, we _should_ reassign all the ports, but we've not always done that and it's also tricky.

Thinking about this now, I feel that we can simplify our lives a lot if we remove the attributes for the routers' internal and control ports and instead assign these (as well as the monitoring port) in a fixed scheme based on the router ID.
This leaves only the external border router interface ports in category a), and it eliminates category b). If we keep using the 50000-range for the external ports, this will give use very clearly distinct ports and low chance of conflicts.
The PortMap would then only be used for external interface ports; we can just limit it to the 50000-range and don't worry about any of the other ports.
