### ISSUE TITLE
How to assign a specific routing path?

### ISSUE THREAD

**Issue by Memtwo** [netsec-ethz/scionlab#333]
Shall I create several ASes and change their route tables? Or any other operations？
By the way, can we users change the scion header formats?

**Comment by marcfrei** [comment]
Hi Memtwo,

> How to assign a specific routing path?

End hosts can query and select available end-to-end paths for every packet they want to send. The selected path information is carried in the packet headers.

An example for how to select an end-to-end path can be found in the main function of the bwtester example

https://github.com/netsec-ethz/scion-apps/blob/1303741ab6b629b46ac0d5c9dc7dc5055082d527/bwtester/bwtestclient/bwtestclient.go#L299

which is using the appnet path selection functionality in 

https://github.com/netsec-ethz/scion-apps/blob/master/pkg/appnet/path_selection.go

For another, more low-level example, please see also the function ChoosePath in 

https://github.com/scionproto/scion/blob/cc7ec7beec83b4262636ac86b244f5ad0fb0d5a7/go/pkg/app/helper.go#L64

> By the way, can we users change the scion header formats?

Since changing the SCION header format would have consequences for the entire infrastructure, this would require a design proposal, detailed discussions, and a pull request for the core code base in the repository 

https://github.com/scionproto/scion

On the other hand, users shouldn't actually need to change the SCION header format, like they don't change the IPv4, IPv6 header format. SCION is extensible through the support of custom header extensions and in many cases a custom application layer header or message type would be a better option.

With kind regards, Marc
