### ISSUE TITLE
User AS: transition from old Coordinator to new one

### ISSUE THREAD

**Issue by juagargi** [netsec-ethz/scionlab#80]
Plan and validate and implement the solution.
The requirements are:
- User ASes running automated updates will continue working seamlessly.
- There will be a script (or similar tool) to update dedicated machines running user ASes.
- Both VPN and direct connection must be supported.
- The ASes are authenticated via `account_id` and `account_secret` at least the first time they contact the new Coordinator.

**Comment by matzf** [comment]
Questions/thoughts:
* Where do we store/serve the installation and update scripts that are currently fetched from `github.com/netsec-ethz/scion-coord`? 
I think my preference would be to serve this file from the coordinator webserver so that it is tied to the version of the software running there.
* ok, only one question for now.

**Comment by juagargi** [comment]
The new installation / update scripts could be served from the new Coordinator. We will give ourselves a deadline after which we can archive/remove the old `scion-coord` github project. All user ASes trying to reach the old URL will fail, but this will be alright.
