### ISSUE TITLE
UserAS: keep VPNClient object when switching AP

### ISSUE THREAD

**Issue by matzf** [netsec-ethz/scionlab#92]
Currently, a separate VPNClient object per attachment point is created. This implies that we use separate VPN client certificates per attachment point. This is unnecessary as we use a common CA for all the VPNs.
Instead, we can keep the VPNClient-object and just switch it to a different VPN (which then only needs to assign a new free IP).

Also, de-activating the VPNClient should free the IP reservation.

**Comment by FR4NK-W** [comment]
>Also, de-activating the VPNClient should free the IP reservation.


This is no longer necessary / useful, I think, since we have a large enough pool of client IPs now.
People should not rely on client VPN IP having a static mapping to ASN, but we should not make things harder for our users if we don't have to.
Or was there an other reason for freeing the IP reservation besides resource preservation? (@matzf)
